### ISSUE TITLE
Code refactoring and reengineering needed

### ISSUE THREAD

**Issue by antonsukhanov** [antiDentite/squareMatrix#1]
**Hello!**

For educational purposes I started developing my implementation of square matrix class. Just for fun I decided to search similar projects on the GitHub and found your repository. 

I should say that your code is extremely hard to read and follow. For example, I found out that in your code there are too much blank lines and no any indentions.

In addition, I'd like to say that your understanding of .h files is not quite clear. In such file you are to implement 'interface' of your class. In 'README.md' you said that users of your class are to include both .h and .cpp files - it's wrong and very bad. In perfect world we just includes .h file (interface) into our main program.

I advice you to look on the **Google C++ Style Guide**.  Your implementation is interesting for me, because I learn programming, but it is very hard to read it :)

**Comment by martynovmaxim** [comment]
I will help you, my friend)

**Comment by antiDentite** [comment]
Hi Anton, 

I should have mentioned in the README file why I have an include statement for a cpp file. It took me a little while to remember why I had decided to do this. First, the classes are template classes which support the possibility of using different types of floating point numbers (such as a multi-precision floating library) and the declaration of these classes is done in the square.h file. Second, you will notice that all the code  is defined in a separate file called square.cpp. This is the usual way of doing things -- you declare classes in the header file and then put the code in a separate source file. The source file is then compiled and all you have to do is link it with other .o files. This will not work with template classes -- you can't just compile square.cpp and then link with other files. What you can do, however, is initialize some instances of the template class in the square.cpp file and then it would work. For instance, if I always used type "double" or "mpfr" then I think I could actually modify the square.cpp file in such a way that I would be able to link square.o to say main.o or other object files.  

I understand the dangers of having an include statement for a cpp file. This is not very convenient when you have a standard include directory (for header files) and your cpp file is somewhere else. As I have mentioned above, there is a good reason for having that square.cpp file not completely dumped into square.h and then deleted. I could just copy the contents of square.cpp into square.h, keep the square.cpp, and then add an explanation in the README file. I will have to review this project as I have not looked at it for months. 

As for the code being hard to understand... Well this is just a bad habit of mine when it comes to writing up the code. I thought that github would automatically convert the code into a typical style but it appears that it doesn't do it. My apologies. I will check if my IDE could convert the code to a standard and more accessible format.

**Comment by antiDentite** [comment]
There is a source code style formatter in codeblocks which enables me to convert the code into 'AStyle'.  I also saw that I have 

#ifndef LINALG_H_INCLUDED
#define LINALG_H_INCLUDED

in the SQUARE.h file. This has to be changed. I will commit the changes later in the day.
